apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-apache
  #annotations:
  #  nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  #ingressClassName: nginx-example
  rules:
  - host: test.nur
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apache
            port:
              number: 80

